name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      REACT_APP_BEE_HOST: https://api.test-node.staging.ethswarm.org/

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm deps
        run: npm ci

      - name: Commit linting
        uses: wagoid/commitlint-github-action@v2

      - name: Code linting
        run: npm run lint:check
        env:
          CI: true

      - name: Dependency check
        run: npm run depcheck

      - name: Types check
        run: npm run check:types

      - name: Build
        run: npm run build

      - name: Build Component
        run: npm run build:component

      - name: Create preview
        uses: ethersphere/swarm-actions/pr-preview@v1
        continue-on-error: true
        with:
          bee-url: https://unlimited.gateway.ethswarm.org
          token: ${{ secrets.GHA_PAT_BASIC }}
          error-document: index.html
          headers: '${{ secrets.GATEWAY_AUTHORIZATION_HEADER }}'

      - name: Upload to testnet
        uses: ethersphere/swarm-actions/upload-dir@v1
        continue-on-error: true
        with:
          index-document: index.html
          error-document: index.html
          dir: ./build
          bee-url: https://api.gateway.testnet.ethswarm.org
